### ISSUE TITLE
[Question] Multi-Speaker Training

### ISSUE THREAD

**Issue by sooftware** [rishikksh20/VocGAN#13]
Hi rishikksh20!! Thank you for your excellent code.  
I have a question about multi-speaker training.  
  
Can I train VocGAN in a multi-speaker environment?  
I used WaveRNN, trained with five speakers. I want to know if this VocGAN is also possible, and if it is possible, will it be a little lower in sound quality?  
  
Thank You!

**Comment by Jackson-Kang** [comment]
Hello, @sooftware .

For satisfying my curiosity, I trained with [VCTK](https://www.kaggle.com/mfekadu/english-multispeaker-corpus-for-voice-cloning), [LJ-Speech](https://keithito.com/LJ-Speech-Dataset/), [KSS](https://www.kaggle.com/bryanpark/korean-single-speaker-speech-dataset), and [Korean Emotional Speech dataset](https://www.aihub.or.kr/keti_data_board/expression)  at once.

Unfortunately, in this case, modified-VocGAN produces noisy samples.


What about using [Hifi-GAN](https://arxiv.org/pdf/2010.05646.pdf)?
In the paper, the authors provide experimental results regarding unseen speakers.

**Comment by sooftware** [comment]
Thank you!  @Jackson-Kang. 
I used WaveRNN (five speakers).   
WaveRNN's result is good.  
So I was wondering what VocGAN would be like.
