### ISSUE TITLE
Should there be any changes in the inference code for Korean inputs?

### ISSUE THREAD

**Issue by jodumagpi** [rishikksh20/VocGAN#23]
Hi! I noticed that you have a pretrained model trained on KSS dataset and I have trained a mel synthesizer model on the same dataset. When I use Griffin-Lim algorithm to reconstruct the linear output, I get a good enough generated speech. However, when I used the mel output of the synthesizer as the input to your model, the output is 11 seconds of nothing. Should there be any modifications when using Korean inputs?

**Comment by Jackson-Kang** [comment]
Hello @jodumagpi ,

When I train the model, I change the sampling rate  with 22050.
(i.e., 44100 -> 22050)

I recommend that test with ground-truth input first, so that you can check whether vocoder is problematic or not.

**Comment by jodumagpi** [comment]
Hi! Thank you! It works now. But the problem was really with the mel input. When I used a different synthesizer to generate the mel, it worked.

**Comment by Jackson-Kang** [comment]
> Hi! Thank you! It works now. But the problem was really with the mel input. When I used a different synthesizer to generate the mel, it worked.

That must be the problem of Text2Mel network. However, keep in mind that the pretrained model trained with KSS dataset only converts female voices. 

If you want to generalize VocGAN for unkown speakers, you must train the VocGAN from scratch using massive and diverse speech dataset.

Thank you.
