### ISSUE TITLE
Any pretrained models?

### ISSUE THREAD

**Issue by Datasciensyash** [rishikksh20/VocGAN#4]
Hello! 
Are there any pretrained models available? 

Also, big thanks for your beautiful repo 🤩

**Comment by rishikksh20** [comment]
I have train this model on custom female dataset and it's working fine, but I haven't train this model on any open source dataset like LJSpeech so I am not able to share the pretrain models.

**Comment by Jackson-Kang** [comment]
Hi, @Datasciensyash 

I have just uploaded pretrained models for LJSpeech-1.1(English) and KSS(Korean) dataset.
Also, generated audio samples can be available.

Plz check the bottom of README.md.
Hope that this contribution is helpful.

Thank you.
